# Generated by Django 3.2.5 on 2021-07-03 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EAT_OUT', 'eating out'), ('HOUSE_SUPPLIES', 'small house item purchase'), ('TAKE_OUT', 'take out'), ('COFFEE', 'coffee')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shop', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('bought_for', models.CharField(choices=[('MICHELLE', 'just michelle'), ('MICHAEL', 'just michael'), ('BOTH', 'both of us')], max_length=200)),
                ('purchase_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_type', to='main.purchasetype')),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
