# Generated by Django 3.2.5 on 2021-07-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210703_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetype',
            name='type',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
