# Generated by Django 3.2.5 on 2021-07-06 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='bought_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_for_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
