# Generated by Django 3.2.5 on 2021-07-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_purchase_bought_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='bought_for',
            field=models.CharField(max_length=200),
        ),
    ]
