# Generated by Django 3.2.5 on 2021-07-31 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_interpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpayment',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
