# Generated by Django 3.2.5 on 2021-08-02 22:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_auto_20210731_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paycheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paychecks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
